[db]
host                    = "8.210.97.145"
port                    = 5001
user                    = "root"
password                = "password"
db_name                 = "xdog-push"

[uri]
pair                    = "http://8.210.97.145:5006/univ2/pair/"