// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.1
// source: proto/uni.proto

package uni

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ClientStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stroke int64 `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
}

func (x *ClientStreamRequest) Reset() {
	*x = ClientStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamRequest) ProtoMessage() {}

func (x *ClientStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamRequest.ProtoReflect.Descriptor instead.
func (*ClientStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{2}
}

func (x *ClientStreamRequest) GetStroke() int64 {
	if x != nil {
		return x.Stroke
	}
	return 0
}

type ClientStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ClientStreamResponse) Reset() {
	*x = ClientStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamResponse) ProtoMessage() {}

func (x *ClientStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamResponse.ProtoReflect.Descriptor instead.
func (*ClientStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{3}
}

func (x *ClientStreamResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ServerStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ServerStreamRequest) Reset() {
	*x = ServerStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamRequest) ProtoMessage() {}

func (x *ServerStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamRequest.ProtoReflect.Descriptor instead.
func (*ServerStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{4}
}

func (x *ServerStreamRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ServerStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ServerStreamResponse) Reset() {
	*x = ServerStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamResponse) ProtoMessage() {}

func (x *ServerStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamResponse.ProtoReflect.Descriptor instead.
func (*ServerStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{5}
}

func (x *ServerStreamResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BidiStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stroke int64 `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
}

func (x *BidiStreamRequest) Reset() {
	*x = BidiStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidiStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiStreamRequest) ProtoMessage() {}

func (x *BidiStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiStreamRequest.ProtoReflect.Descriptor instead.
func (*BidiStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{6}
}

func (x *BidiStreamRequest) GetStroke() int64 {
	if x != nil {
		return x.Stroke
	}
	return 0
}

type BidiStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stroke int64 `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
}

func (x *BidiStreamResponse) Reset() {
	*x = BidiStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidiStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiStreamResponse) ProtoMessage() {}

func (x *BidiStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiStreamResponse.ProtoReflect.Descriptor instead.
func (*BidiStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{7}
}

func (x *BidiStreamResponse) GetStroke() int64 {
	if x != nil {
		return x.Stroke
	}
	return 0
}

type SignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Sign    string `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{8}
}

func (x *SignRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *SignRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type SignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{9}
}

func (x *SignResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type CheckSignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *CheckSignRequest) Reset() {
	*x = CheckSignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSignRequest) ProtoMessage() {}

func (x *CheckSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSignRequest.ProtoReflect.Descriptor instead.
func (*CheckSignRequest) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{10}
}

func (x *CheckSignRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CheckSignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CheckSignResponse) Reset() {
	*x = CheckSignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSignResponse) ProtoMessage() {}

func (x *CheckSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSignResponse.ProtoReflect.Descriptor instead.
func (*CheckSignResponse) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{11}
}

func (x *CheckSignResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type ApproveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Sign    string `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{12}
}

func (x *ApproveRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ApproveRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApproveRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *ApproveRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ApproveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ApproveResponse) Reset() {
	*x = ApproveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResponse) ProtoMessage() {}

func (x *ApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResponse.ProtoReflect.Descriptor instead.
func (*ApproveResponse) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{13}
}

func (x *ApproveResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FlashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Sign    string  `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	Address string  `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Token   string  `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Amount  float32 `protobuf:"fixed32,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Command string  `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *FlashRequest) Reset() {
	*x = FlashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashRequest) ProtoMessage() {}

func (x *FlashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashRequest.ProtoReflect.Descriptor instead.
func (*FlashRequest) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{14}
}

func (x *FlashRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FlashRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *FlashRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *FlashRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *FlashRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FlashRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type FlashResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *FlashResponse) Reset() {
	*x = FlashResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashResponse) ProtoMessage() {}

func (x *FlashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashResponse.ProtoReflect.Descriptor instead.
func (*FlashResponse) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{15}
}

func (x *FlashResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Pool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Liquidity            float32 `protobuf:"fixed32,1,opt,name=liquidity,proto3" json:"liquidity,omitempty"`
	Vols                 float32 `protobuf:"fixed32,2,opt,name=vols,proto3" json:"vols,omitempty"`
	Txs                  int64   `protobuf:"varint,3,opt,name=txs,proto3" json:"txs,omitempty"`
	Traders              int64   `protobuf:"varint,4,opt,name=traders,proto3" json:"traders,omitempty"`
	Age                  string  `protobuf:"bytes,5,opt,name=age,proto3" json:"age,omitempty"`
	IsTransferPause      bool    `protobuf:"varint,6,opt,name=isTransferPause,proto3" json:"isTransferPause,omitempty"`
	IsSlippageModifiable bool    `protobuf:"varint,7,opt,name=isSlippageModifiable,proto3" json:"isSlippageModifiable,omitempty"`
	IsBlackList          bool    `protobuf:"varint,8,opt,name=isBlackList,proto3" json:"isBlackList,omitempty"`
	IsWhiteList          bool    `protobuf:"varint,9,opt,name=isWhiteList,proto3" json:"isWhiteList,omitempty"`
	IsCoolDown           bool    `protobuf:"varint,10,opt,name=isCoolDown,proto3" json:"isCoolDown,omitempty"`
	BuyTax               float32 `protobuf:"fixed32,11,opt,name=buyTax,proto3" json:"buyTax,omitempty"`
	SellTax              float32 `protobuf:"fixed32,12,opt,name=sellTax,proto3" json:"sellTax,omitempty"`
	IsBuy                bool    `protobuf:"varint,13,opt,name=isBuy,proto3" json:"isBuy,omitempty"`
	IsSellAll            bool    `protobuf:"varint,14,opt,name=isSellAll,proto3" json:"isSellAll,omitempty"`
	Token                string  `protobuf:"bytes,15,opt,name=token,proto3" json:"token,omitempty"`
	Price                float32 `protobuf:"fixed32,16,opt,name=price,proto3" json:"price,omitempty"`
	Symbol               string  `protobuf:"bytes,17,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Twitter              int64   `protobuf:"varint,18,opt,name=twitter,proto3" json:"twitter,omitempty"`
	HiddenOwner          bool    `protobuf:"varint,19,opt,name=hiddenOwner,proto3" json:"hiddenOwner,omitempty"`
}

func (x *Pool) Reset() {
	*x = Pool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{16}
}

func (x *Pool) GetLiquidity() float32 {
	if x != nil {
		return x.Liquidity
	}
	return 0
}

func (x *Pool) GetVols() float32 {
	if x != nil {
		return x.Vols
	}
	return 0
}

func (x *Pool) GetTxs() int64 {
	if x != nil {
		return x.Txs
	}
	return 0
}

func (x *Pool) GetTraders() int64 {
	if x != nil {
		return x.Traders
	}
	return 0
}

func (x *Pool) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *Pool) GetIsTransferPause() bool {
	if x != nil {
		return x.IsTransferPause
	}
	return false
}

func (x *Pool) GetIsSlippageModifiable() bool {
	if x != nil {
		return x.IsSlippageModifiable
	}
	return false
}

func (x *Pool) GetIsBlackList() bool {
	if x != nil {
		return x.IsBlackList
	}
	return false
}

func (x *Pool) GetIsWhiteList() bool {
	if x != nil {
		return x.IsWhiteList
	}
	return false
}

func (x *Pool) GetIsCoolDown() bool {
	if x != nil {
		return x.IsCoolDown
	}
	return false
}

func (x *Pool) GetBuyTax() float32 {
	if x != nil {
		return x.BuyTax
	}
	return 0
}

func (x *Pool) GetSellTax() float32 {
	if x != nil {
		return x.SellTax
	}
	return 0
}

func (x *Pool) GetIsBuy() bool {
	if x != nil {
		return x.IsBuy
	}
	return false
}

func (x *Pool) GetIsSellAll() bool {
	if x != nil {
		return x.IsSellAll
	}
	return false
}

func (x *Pool) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Pool) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Pool) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Pool) GetTwitter() int64 {
	if x != nil {
		return x.Twitter
	}
	return 0
}

func (x *Pool) GetHiddenOwner() bool {
	if x != nil {
		return x.HiddenOwner
	}
	return false
}

type FlashBuyAutoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pool *Pool `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
}

func (x *FlashBuyAutoRequest) Reset() {
	*x = FlashBuyAutoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashBuyAutoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashBuyAutoRequest) ProtoMessage() {}

func (x *FlashBuyAutoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashBuyAutoRequest.ProtoReflect.Descriptor instead.
func (*FlashBuyAutoRequest) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{17}
}

func (x *FlashBuyAutoRequest) GetPool() *Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

type FlashBuyAutoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *FlashBuyAutoResponse) Reset() {
	*x = FlashBuyAutoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashBuyAutoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashBuyAutoResponse) ProtoMessage() {}

func (x *FlashBuyAutoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashBuyAutoResponse.ProtoReflect.Descriptor instead.
func (*FlashBuyAutoResponse) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{18}
}

func (x *FlashBuyAutoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FlashBuyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Amount float32 `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *FlashBuyRequest) Reset() {
	*x = FlashBuyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashBuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashBuyRequest) ProtoMessage() {}

func (x *FlashBuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashBuyRequest.ProtoReflect.Descriptor instead.
func (*FlashBuyRequest) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{19}
}

func (x *FlashBuyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *FlashBuyRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type FlashBuyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *FlashBuyResponse) Reset() {
	*x = FlashBuyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashBuyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashBuyResponse) ProtoMessage() {}

func (x *FlashBuyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashBuyResponse.ProtoReflect.Descriptor instead.
func (*FlashBuyResponse) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{20}
}

func (x *FlashBuyResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address              string  `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Turn                 int64   `protobuf:"varint,2,opt,name=turn,proto3" json:"turn,omitempty"`
	PrivateKey           string  `protobuf:"bytes,3,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	MaxPerSwap           float32 `protobuf:"fixed32,4,opt,name=maxPerSwap,proto3" json:"maxPerSwap,omitempty"`
	PoolPercent          float32 `protobuf:"fixed32,5,opt,name=poolPercent,proto3" json:"poolPercent,omitempty"`
	Liquidity            float32 `protobuf:"fixed32,6,opt,name=liquidity,proto3" json:"liquidity,omitempty"`
	Vols                 float32 `protobuf:"fixed32,7,opt,name=vols,proto3" json:"vols,omitempty"`
	Txs                  int64   `protobuf:"varint,8,opt,name=txs,proto3" json:"txs,omitempty"`
	Traders              int64   `protobuf:"varint,9,opt,name=traders,proto3" json:"traders,omitempty"`
	GasPrice             int64   `protobuf:"varint,10,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Rpc                  string  `protobuf:"bytes,11,opt,name=rpc,proto3" json:"rpc,omitempty"`
	Receipt              string  `protobuf:"bytes,12,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Age                  int64   `protobuf:"varint,13,opt,name=age,proto3" json:"age,omitempty"`
	Level                int64   `protobuf:"varint,14,opt,name=level,proto3" json:"level,omitempty"`
	IsCoolDown           bool    `protobuf:"varint,15,opt,name=isCoolDown,proto3" json:"isCoolDown,omitempty"`
	IsTransferPause      bool    `protobuf:"varint,16,opt,name=isTransferPause,proto3" json:"isTransferPause,omitempty"`
	IsSlippageModifiable bool    `protobuf:"varint,17,opt,name=isSlippageModifiable,proto3" json:"isSlippageModifiable,omitempty"`
	IsBlackList          bool    `protobuf:"varint,18,opt,name=isBlackList,proto3" json:"isBlackList,omitempty"`
	IsWhiteList          bool    `protobuf:"varint,19,opt,name=isWhiteList,proto3" json:"isWhiteList,omitempty"`
	BuyTax               float32 `protobuf:"fixed32,20,opt,name=buyTax,proto3" json:"buyTax,omitempty"`
	SellTax              float32 `protobuf:"fixed32,21,opt,name=sellTax,proto3" json:"sellTax,omitempty"`
	IsBuy                bool    `protobuf:"varint,22,opt,name=isBuy,proto3" json:"isBuy,omitempty"`
	IsSellAll            bool    `protobuf:"varint,23,opt,name=isSellAll,proto3" json:"isSellAll,omitempty"`
	Slippage             int64   `protobuf:"varint,24,opt,name=slippage,proto3" json:"slippage,omitempty"`
	Twitter              int64   `protobuf:"varint,25,opt,name=twitter,proto3" json:"twitter,omitempty"`
	HiddenOwner          bool    `protobuf:"varint,26,opt,name=hiddenOwner,proto3" json:"hiddenOwner,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{21}
}

func (x *User) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *User) GetTurn() int64 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *User) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *User) GetMaxPerSwap() float32 {
	if x != nil {
		return x.MaxPerSwap
	}
	return 0
}

func (x *User) GetPoolPercent() float32 {
	if x != nil {
		return x.PoolPercent
	}
	return 0
}

func (x *User) GetLiquidity() float32 {
	if x != nil {
		return x.Liquidity
	}
	return 0
}

func (x *User) GetVols() float32 {
	if x != nil {
		return x.Vols
	}
	return 0
}

func (x *User) GetTxs() int64 {
	if x != nil {
		return x.Txs
	}
	return 0
}

func (x *User) GetTraders() int64 {
	if x != nil {
		return x.Traders
	}
	return 0
}

func (x *User) GetGasPrice() int64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

func (x *User) GetRpc() string {
	if x != nil {
		return x.Rpc
	}
	return ""
}

func (x *User) GetReceipt() string {
	if x != nil {
		return x.Receipt
	}
	return ""
}

func (x *User) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *User) GetIsCoolDown() bool {
	if x != nil {
		return x.IsCoolDown
	}
	return false
}

func (x *User) GetIsTransferPause() bool {
	if x != nil {
		return x.IsTransferPause
	}
	return false
}

func (x *User) GetIsSlippageModifiable() bool {
	if x != nil {
		return x.IsSlippageModifiable
	}
	return false
}

func (x *User) GetIsBlackList() bool {
	if x != nil {
		return x.IsBlackList
	}
	return false
}

func (x *User) GetIsWhiteList() bool {
	if x != nil {
		return x.IsWhiteList
	}
	return false
}

func (x *User) GetBuyTax() float32 {
	if x != nil {
		return x.BuyTax
	}
	return 0
}

func (x *User) GetSellTax() float32 {
	if x != nil {
		return x.SellTax
	}
	return 0
}

func (x *User) GetIsBuy() bool {
	if x != nil {
		return x.IsBuy
	}
	return false
}

func (x *User) GetIsSellAll() bool {
	if x != nil {
		return x.IsSellAll
	}
	return false
}

func (x *User) GetSlippage() int64 {
	if x != nil {
		return x.Slippage
	}
	return 0
}

func (x *User) GetTwitter() int64 {
	if x != nil {
		return x.Twitter
	}
	return 0
}

func (x *User) GetHiddenOwner() bool {
	if x != nil {
		return x.HiddenOwner
	}
	return false
}

type GetFlashUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Sign    string `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetFlashUserRequest) Reset() {
	*x = GetFlashUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlashUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlashUserRequest) ProtoMessage() {}

func (x *GetFlashUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlashUserRequest.ProtoReflect.Descriptor instead.
func (*GetFlashUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{22}
}

func (x *GetFlashUserRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFlashUserRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *GetFlashUserRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetFlashUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GetFlashUserResponse) Reset() {
	*x = GetFlashUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlashUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlashUserResponse) ProtoMessage() {}

func (x *GetFlashUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlashUserResponse.ProtoReflect.Descriptor instead.
func (*GetFlashUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{23}
}

func (x *GetFlashUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetFlashUserResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SaveFlashUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Sign    string `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	User    *User  `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *SaveFlashUserRequest) Reset() {
	*x = SaveFlashUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveFlashUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFlashUserRequest) ProtoMessage() {}

func (x *SaveFlashUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFlashUserRequest.ProtoReflect.Descriptor instead.
func (*SaveFlashUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{24}
}

func (x *SaveFlashUserRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SaveFlashUserRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *SaveFlashUserRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SaveFlashUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SaveFlashUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SaveFlashUserResponse) Reset() {
	*x = SaveFlashUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveFlashUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFlashUserResponse) ProtoMessage() {}

func (x *SaveFlashUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFlashUserResponse.ProtoReflect.Descriptor instead.
func (*SaveFlashUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{25}
}

func (x *SaveFlashUserResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Swap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Symbol  string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Cost    string                 `protobuf:"bytes,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Buy     string                 `protobuf:"bytes,4,opt,name=buy,proto3" json:"buy,omitempty"`
	Now     string                 `protobuf:"bytes,5,opt,name=now,proto3" json:"now,omitempty"`
	Price   string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	BuyTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=buyTime,proto3" json:"buyTime,omitempty"`
	Hash    string                 `protobuf:"bytes,8,opt,name=hash,proto3" json:"hash,omitempty"`
	IsSell  int64                  `protobuf:"varint,9,opt,name=isSell,proto3" json:"isSell,omitempty"`
}

func (x *Swap) Reset() {
	*x = Swap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Swap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Swap) ProtoMessage() {}

func (x *Swap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Swap.ProtoReflect.Descriptor instead.
func (*Swap) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{26}
}

func (x *Swap) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Swap) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Swap) GetCost() string {
	if x != nil {
		return x.Cost
	}
	return ""
}

func (x *Swap) GetBuy() string {
	if x != nil {
		return x.Buy
	}
	return ""
}

func (x *Swap) GetNow() string {
	if x != nil {
		return x.Now
	}
	return ""
}

func (x *Swap) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Swap) GetBuyTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BuyTime
	}
	return nil
}

func (x *Swap) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Swap) GetIsSell() int64 {
	if x != nil {
		return x.IsSell
	}
	return 0
}

type GetFlashSwapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Sign    string `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetFlashSwapRequest) Reset() {
	*x = GetFlashSwapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlashSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlashSwapRequest) ProtoMessage() {}

func (x *GetFlashSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlashSwapRequest.ProtoReflect.Descriptor instead.
func (*GetFlashSwapRequest) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{27}
}

func (x *GetFlashSwapRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFlashSwapRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *GetFlashSwapRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetFlashSwapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Swap []*Swap `protobuf:"bytes,1,rep,name=swap,proto3" json:"swap,omitempty"`
	Msg  string  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GetFlashSwapResponse) Reset() {
	*x = GetFlashSwapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_uni_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFlashSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlashSwapResponse) ProtoMessage() {}

func (x *GetFlashSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_uni_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlashSwapResponse.ProtoReflect.Descriptor instead.
func (*GetFlashSwapResponse) Descriptor() ([]byte, []int) {
	return file_proto_uni_proto_rawDescGZIP(), []int{28}
}

func (x *GetFlashSwapResponse) GetSwap() []*Swap {
	if x != nil {
		return x.Swap
	}
	return nil
}

func (x *GetFlashSwapResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_uni_proto protoreflect.FileDescriptor

var file_proto_uni_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x6e, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x75, 0x6e, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x20, 0x0a, 0x0c, 0x43, 0x61,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2d, 0x0a, 0x13,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x22, 0x2c, 0x0a, 0x14, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2b, 0x0a, 0x13, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x14, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2b, 0x0a, 0x11, 0x42, 0x69, 0x64, 0x69, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72,
	0x6f, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x72, 0x6f, 0x6b,
	0x65, 0x22, 0x2c, 0x0a, 0x12, 0x42, 0x69, 0x64, 0x69, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x6f, 0x6b,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x22,
	0x55, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x26, 0x0a, 0x0c, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2c,
	0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x2b, 0x0a, 0x11,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x6e, 0x0a, 0x0e, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x23, 0x0a, 0x0f, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x9e,
	0x01, 0x0a, 0x0c, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22,
	0x21, 0x0a, 0x0d, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x9e, 0x04, 0x0a, 0x04, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09,
	0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6f, 0x6c,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x76, 0x6f, 0x6c, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x78, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x78, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x69,
	0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x50, 0x61, 0x75, 0x73, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x50, 0x61, 0x75, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x69, 0x73, 0x53, 0x6c, 0x69, 0x70, 0x70,
	0x61, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x14, 0x69, 0x73, 0x53, 0x6c, 0x69, 0x70, 0x70, 0x61, 0x67, 0x65, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x69, 0x73, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x69,
	0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x69, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x69, 0x73, 0x43, 0x6f, 0x6f, 0x6c, 0x44, 0x6f, 0x77, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x69, 0x73, 0x43, 0x6f, 0x6f, 0x6c, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x75, 0x79, 0x54, 0x61, 0x78, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x62,
	0x75, 0x79, 0x54, 0x61, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x6c, 0x6c, 0x54, 0x61, 0x78,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x73, 0x65, 0x6c, 0x6c, 0x54, 0x61, 0x78, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x73, 0x42, 0x75, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x69, 0x73, 0x42, 0x75, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x6c, 0x41,
	0x6c, 0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x6c,
	0x41, 0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x77, 0x69, 0x74, 0x74,
	0x65, 0x72, 0x18, 0x12, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65,
	0x72, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x18, 0x13, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x22, 0x34, 0x0a, 0x13, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x42, 0x75, 0x79, 0x41,
	0x75, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x70, 0x6f,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x50,
	0x6f, 0x6f, 0x6c, 0x52, 0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x22, 0x28, 0x0a, 0x14, 0x46, 0x6c, 0x61,
	0x73, 0x68, 0x42, 0x75, 0x79, 0x41, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x3f, 0x0a, 0x0f, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x42, 0x75, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x24, 0x0a, 0x10, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x42, 0x75, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xe4, 0x05, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x75, 0x72,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x50, 0x65, 0x72, 0x53, 0x77, 0x61, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x50, 0x65, 0x72, 0x53, 0x77, 0x61,
	0x70, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6f, 0x6f, 0x6c, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x70, 0x6f, 0x6f, 0x6c, 0x50, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6f, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x04, 0x76, 0x6f, 0x6c, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x78, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x74, 0x78, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x70, 0x63, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x70, 0x63, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x43, 0x6f, 0x6f, 0x6c, 0x44, 0x6f, 0x77, 0x6e, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x43, 0x6f, 0x6f, 0x6c, 0x44, 0x6f, 0x77,
	0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x50,
	0x61, 0x75, 0x73, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x50, 0x61, 0x75, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x69,
	0x73, 0x53, 0x6c, 0x69, 0x70, 0x70, 0x61, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x69, 0x73, 0x53, 0x6c, 0x69,
	0x70, 0x70, 0x61, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x69, 0x73, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x12,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x13, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x79, 0x54, 0x61, 0x78, 0x18, 0x14, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x62, 0x75, 0x79, 0x54, 0x61, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x65, 0x6c, 0x6c, 0x54, 0x61, 0x78, 0x18, 0x15, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x73, 0x65,
	0x6c, 0x6c, 0x54, 0x61, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x42, 0x75, 0x79, 0x18, 0x16,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x42, 0x75, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x69,
	0x73, 0x53, 0x65, 0x6c, 0x6c, 0x41, 0x6c, 0x6c, 0x18, 0x17, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x69, 0x73, 0x53, 0x65, 0x6c, 0x6c, 0x41, 0x6c, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6c, 0x69,
	0x70, 0x70, 0x61, 0x67, 0x65, 0x18, 0x18, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x6c, 0x69,
	0x70, 0x70, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72,
	0x18, 0x19, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x12,
	0x20, 0x0a, 0x0b, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x1a,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x22, 0x5d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x47, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x7d, 0x0a, 0x14, 0x53, 0x61, 0x76,
	0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x29, 0x0a, 0x15, 0x53, 0x61, 0x76, 0x65,
	0x46, 0x6c, 0x61, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0xe4, 0x01, 0x0a, 0x04, 0x53, 0x77, 0x61, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x62, 0x75, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x75, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x6f, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e,
	0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x62, 0x75, 0x79, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x62, 0x75, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x6c, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x6c, 0x22, 0x5d, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x47, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x04, 0x73, 0x77, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x52, 0x04, 0x73, 0x77, 0x61, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x32, 0xbc, 0x06, 0x0a, 0x03, 0x55, 0x6e, 0x69, 0x12, 0x2d, 0x0a, 0x04, 0x43, 0x61,
	0x6c, 0x6c, 0x12, 0x10, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x18, 0x2e, 0x75, 0x6e, 0x69, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x12, 0x47, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x18, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x75,
	0x6e, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x43, 0x0a, 0x0a, 0x42,
	0x69, 0x64, 0x69, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x16, 0x2e, 0x75, 0x6e, 0x69, 0x2e,
	0x42, 0x69, 0x64, 0x69, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x42, 0x69, 0x64, 0x69, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x45, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x18, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x75, 0x6e, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0d, 0x53, 0x61, 0x76, 0x65, 0x46,
	0x6c, 0x61, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x53,
	0x61, 0x76, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x46, 0x6c,
	0x61, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x45, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x77, 0x61,
	0x70, 0x12, 0x18, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68,
	0x53, 0x77, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x75, 0x6e,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x77, 0x61, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e,
	0x12, 0x10, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x53, 0x69, 0x67, 0x6e, 0x12, 0x15, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x75, 0x6e,
	0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x12, 0x13, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a,
	0x05, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x12, 0x11, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x46, 0x6c, 0x61,
	0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x75, 0x6e, 0x69, 0x2e,
	0x46, 0x6c, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x39, 0x0a, 0x08, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x42, 0x75, 0x79, 0x12, 0x14, 0x2e, 0x75, 0x6e,
	0x69, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x42, 0x75, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x42, 0x75, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x46, 0x6c,
	0x61, 0x73, 0x68, 0x42, 0x75, 0x79, 0x41, 0x75, 0x74, 0x6f, 0x12, 0x18, 0x2e, 0x75, 0x6e, 0x69,
	0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x42, 0x75, 0x79, 0x41, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x75, 0x6e, 0x69, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68,
	0x42, 0x75, 0x79, 0x41, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x75, 0x6e, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_uni_proto_rawDescOnce sync.Once
	file_proto_uni_proto_rawDescData = file_proto_uni_proto_rawDesc
)

func file_proto_uni_proto_rawDescGZIP() []byte {
	file_proto_uni_proto_rawDescOnce.Do(func() {
		file_proto_uni_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_uni_proto_rawDescData)
	})
	return file_proto_uni_proto_rawDescData
}

var file_proto_uni_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_uni_proto_goTypes = []interface{}{
	(*CallRequest)(nil),           // 0: uni.CallRequest
	(*CallResponse)(nil),          // 1: uni.CallResponse
	(*ClientStreamRequest)(nil),   // 2: uni.ClientStreamRequest
	(*ClientStreamResponse)(nil),  // 3: uni.ClientStreamResponse
	(*ServerStreamRequest)(nil),   // 4: uni.ServerStreamRequest
	(*ServerStreamResponse)(nil),  // 5: uni.ServerStreamResponse
	(*BidiStreamRequest)(nil),     // 6: uni.BidiStreamRequest
	(*BidiStreamResponse)(nil),    // 7: uni.BidiStreamResponse
	(*SignRequest)(nil),           // 8: uni.SignRequest
	(*SignResponse)(nil),          // 9: uni.SignResponse
	(*CheckSignRequest)(nil),      // 10: uni.CheckSignRequest
	(*CheckSignResponse)(nil),     // 11: uni.CheckSignResponse
	(*ApproveRequest)(nil),        // 12: uni.ApproveRequest
	(*ApproveResponse)(nil),       // 13: uni.ApproveResponse
	(*FlashRequest)(nil),          // 14: uni.FlashRequest
	(*FlashResponse)(nil),         // 15: uni.FlashResponse
	(*Pool)(nil),                  // 16: uni.Pool
	(*FlashBuyAutoRequest)(nil),   // 17: uni.FlashBuyAutoRequest
	(*FlashBuyAutoResponse)(nil),  // 18: uni.FlashBuyAutoResponse
	(*FlashBuyRequest)(nil),       // 19: uni.FlashBuyRequest
	(*FlashBuyResponse)(nil),      // 20: uni.FlashBuyResponse
	(*User)(nil),                  // 21: uni.User
	(*GetFlashUserRequest)(nil),   // 22: uni.GetFlashUserRequest
	(*GetFlashUserResponse)(nil),  // 23: uni.GetFlashUserResponse
	(*SaveFlashUserRequest)(nil),  // 24: uni.SaveFlashUserRequest
	(*SaveFlashUserResponse)(nil), // 25: uni.SaveFlashUserResponse
	(*Swap)(nil),                  // 26: uni.Swap
	(*GetFlashSwapRequest)(nil),   // 27: uni.GetFlashSwapRequest
	(*GetFlashSwapResponse)(nil),  // 28: uni.GetFlashSwapResponse
	(*timestamppb.Timestamp)(nil), // 29: google.protobuf.Timestamp
}
var file_proto_uni_proto_depIdxs = []int32{
	16, // 0: uni.FlashBuyAutoRequest.pool:type_name -> uni.Pool
	21, // 1: uni.GetFlashUserResponse.user:type_name -> uni.User
	21, // 2: uni.SaveFlashUserRequest.user:type_name -> uni.User
	29, // 3: uni.Swap.buyTime:type_name -> google.protobuf.Timestamp
	26, // 4: uni.GetFlashSwapResponse.swap:type_name -> uni.Swap
	0,  // 5: uni.Uni.Call:input_type -> uni.CallRequest
	2,  // 6: uni.Uni.ClientStream:input_type -> uni.ClientStreamRequest
	4,  // 7: uni.Uni.ServerStream:input_type -> uni.ServerStreamRequest
	6,  // 8: uni.Uni.BidiStream:input_type -> uni.BidiStreamRequest
	22, // 9: uni.Uni.GetFlashUser:input_type -> uni.GetFlashUserRequest
	24, // 10: uni.Uni.SaveFlashUser:input_type -> uni.SaveFlashUserRequest
	27, // 11: uni.Uni.GetFlashSwap:input_type -> uni.GetFlashSwapRequest
	8,  // 12: uni.Uni.Sign:input_type -> uni.SignRequest
	10, // 13: uni.Uni.CheckSign:input_type -> uni.CheckSignRequest
	12, // 14: uni.Uni.Approve:input_type -> uni.ApproveRequest
	14, // 15: uni.Uni.Flash:input_type -> uni.FlashRequest
	19, // 16: uni.Uni.FlashBuy:input_type -> uni.FlashBuyRequest
	17, // 17: uni.Uni.FlashBuyAuto:input_type -> uni.FlashBuyAutoRequest
	1,  // 18: uni.Uni.Call:output_type -> uni.CallResponse
	3,  // 19: uni.Uni.ClientStream:output_type -> uni.ClientStreamResponse
	5,  // 20: uni.Uni.ServerStream:output_type -> uni.ServerStreamResponse
	7,  // 21: uni.Uni.BidiStream:output_type -> uni.BidiStreamResponse
	23, // 22: uni.Uni.GetFlashUser:output_type -> uni.GetFlashUserResponse
	25, // 23: uni.Uni.SaveFlashUser:output_type -> uni.SaveFlashUserResponse
	28, // 24: uni.Uni.GetFlashSwap:output_type -> uni.GetFlashSwapResponse
	9,  // 25: uni.Uni.Sign:output_type -> uni.SignResponse
	11, // 26: uni.Uni.CheckSign:output_type -> uni.CheckSignResponse
	13, // 27: uni.Uni.Approve:output_type -> uni.ApproveResponse
	15, // 28: uni.Uni.Flash:output_type -> uni.FlashResponse
	20, // 29: uni.Uni.FlashBuy:output_type -> uni.FlashBuyResponse
	18, // 30: uni.Uni.FlashBuyAuto:output_type -> uni.FlashBuyAutoResponse
	18, // [18:31] is the sub-list for method output_type
	5,  // [5:18] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_uni_proto_init() }
func file_proto_uni_proto_init() {
	if File_proto_uni_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_uni_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidiStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidiStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApproveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApproveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlashResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlashBuyAutoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlashBuyAutoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlashBuyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlashBuyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlashUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlashUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveFlashUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveFlashUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Swap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlashSwapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_uni_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFlashSwapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_uni_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_uni_proto_goTypes,
		DependencyIndexes: file_proto_uni_proto_depIdxs,
		MessageInfos:      file_proto_uni_proto_msgTypes,
	}.Build()
	File_proto_uni_proto = out.File
	file_proto_uni_proto_rawDesc = nil
	file_proto_uni_proto_goTypes = nil
	file_proto_uni_proto_depIdxs = nil
}
